# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab_04.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 950)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.graphview_circle = QtWidgets.QGraphicsView(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphview_circle.sizePolicy().hasHeightForWidth())
        self.graphview_circle.setSizePolicy(sizePolicy)
        self.graphview_circle.setMinimumSize(QtCore.QSize(1500, 0))
        self.graphview_circle.setObjectName("graphview_circle")
        self.horizontalLayout_4.addWidget(self.graphview_circle)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_create_circle = QtWidgets.QLabel(self.tab)
        self.label_create_circle.setIndent(81)
        self.label_create_circle.setObjectName("label_create_circle")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_create_circle)
        self.label_center_circle = QtWidgets.QLabel(self.tab)
        self.label_center_circle.setObjectName("label_center_circle")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_center_circle)
        self.label_center_x_circle = QtWidgets.QLabel(self.tab)
        self.label_center_x_circle.setObjectName("label_center_x_circle")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_center_x_circle)
        self.edit_center_x_circle = QtWidgets.QLineEdit(self.tab)
        self.edit_center_x_circle.setObjectName("edit_center_x_circle")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_center_x_circle)
        self.label_center_y_circle = QtWidgets.QLabel(self.tab)
        self.label_center_y_circle.setObjectName("label_center_y_circle")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_center_y_circle)
        self.edit_center_y_circle = QtWidgets.QLineEdit(self.tab)
        self.edit_center_y_circle.setObjectName("edit_center_y_circle")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_center_y_circle)
        self.label_radius_circle = QtWidgets.QLabel(self.tab)
        self.label_radius_circle.setObjectName("label_radius_circle")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_radius_circle)
        self.edit_radius_circle = QtWidgets.QLineEdit(self.tab)
        self.edit_radius_circle.setObjectName("edit_radius_circle")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.edit_radius_circle)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.SpanningRole, spacerItem)
        self.label_algorithm_circle = QtWidgets.QLabel(self.tab)
        self.label_algorithm_circle.setObjectName("label_algorithm_circle")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_algorithm_circle)
        self.box_algorithm_circle = QtWidgets.QComboBox(self.tab)
        self.box_algorithm_circle.setObjectName("box_algorithm_circle")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.box_algorithm_circle)
        self.label_colour_circle = QtWidgets.QLabel(self.tab)
        self.label_colour_circle.setObjectName("label_colour_circle")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_colour_circle)
        self.box_colour_circle = QtWidgets.QComboBox(self.tab)
        self.box_colour_circle.setObjectName("box_colour_circle")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.box_colour_circle)
        spacerItem1 = QtWidgets.QSpacerItem(20, 143, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.label_create_spectrum_circle = QtWidgets.QLabel(self.tab)
        self.label_create_spectrum_circle.setIndent(24)
        self.label_create_spectrum_circle.setObjectName("label_create_spectrum_circle")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.label_create_spectrum_circle)
        self.label_start_radius_circle = QtWidgets.QLabel(self.tab)
        self.label_start_radius_circle.setIndent(18)
        self.label_start_radius_circle.setObjectName("label_start_radius_circle")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_start_radius_circle)
        self.edit_start_radius_circle = QtWidgets.QLineEdit(self.tab)
        self.edit_start_radius_circle.setObjectName("edit_start_radius_circle")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.edit_start_radius_circle)
        self.label_step_change_circle = QtWidgets.QLabel(self.tab)
        self.label_step_change_circle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_step_change_circle.setIndent(20)
        self.label_step_change_circle.setObjectName("label_step_change_circle")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_step_change_circle)
        self.edit_step_change_circle = QtWidgets.QLineEdit(self.tab)
        self.edit_step_change_circle.setObjectName("edit_step_change_circle")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.edit_step_change_circle)
        self.radiobut_end_radius = QtWidgets.QRadioButton(self.tab)
        self.radiobut_end_radius.setObjectName("radiobut_end_radius")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.radiobut_end_radius)
        self.edit_end_radius_circle = QtWidgets.QLineEdit(self.tab)
        self.edit_end_radius_circle.setObjectName("edit_end_radius_circle")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.edit_end_radius_circle)
        self.radiobut_count_circles = QtWidgets.QRadioButton(self.tab)
        self.radiobut_count_circles.setObjectName("radiobut_count_circles")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.radiobut_count_circles)
        spacerItem2 = QtWidgets.QSpacerItem(20, 123, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(15, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.but_create_circle = QtWidgets.QPushButton(self.tab)
        self.but_create_circle.setObjectName("but_create_circle")
        self.formLayout.setWidget(16, QtWidgets.QFormLayout.SpanningRole, self.but_create_circle)
        self.but_create_spectrum_circle = QtWidgets.QPushButton(self.tab)
        self.but_create_spectrum_circle.setObjectName("but_create_spectrum_circle")
        self.formLayout.setWidget(17, QtWidgets.QFormLayout.SpanningRole, self.but_create_spectrum_circle)
        self.but_clear_circle = QtWidgets.QPushButton(self.tab)
        self.but_clear_circle.setObjectName("but_clear_circle")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.SpanningRole, self.but_clear_circle)
        self.edit_count_circle = QtWidgets.QLineEdit(self.tab)
        self.edit_count_circle.setObjectName("edit_count_circle")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.edit_count_circle)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 1880, 857))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.graphview_ellipse = QtWidgets.QGraphicsView(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphview_ellipse.sizePolicy().hasHeightForWidth())
        self.graphview_ellipse.setSizePolicy(sizePolicy)
        self.graphview_ellipse.setMinimumSize(QtCore.QSize(1500, 0))
        self.graphview_ellipse.setObjectName("graphview_ellipse")
        self.horizontalLayout_6.addWidget(self.graphview_ellipse)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_build_ellipse = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_build_ellipse.setIndent(97)
        self.label_build_ellipse.setObjectName("label_build_ellipse")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_build_ellipse)
        self.label_center_ellipse = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_center_ellipse.setObjectName("label_center_ellipse")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_center_ellipse)
        self.label_center_x_ellipse = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_center_x_ellipse.setObjectName("label_center_x_ellipse")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_center_x_ellipse)
        self.edit_center_x_ellipse = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edit_center_x_ellipse.setObjectName("edit_center_x_ellipse")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_center_x_ellipse)
        self.label_center_y_ellipse = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_center_y_ellipse.setObjectName("label_center_y_ellipse")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_center_y_ellipse)
        self.edit_center_y_ellipse = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edit_center_y_ellipse.setObjectName("edit_center_y_ellipse")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edit_center_y_ellipse)
        self.label_value_halfaxis_ellipse = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_value_halfaxis_ellipse.setObjectName("label_value_halfaxis_ellipse")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_value_halfaxis_ellipse)
        self.label_big_halfaxis_ellipse = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_big_halfaxis_ellipse.setObjectName("label_big_halfaxis_ellipse")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_big_halfaxis_ellipse)
        self.edit_halfaxis_big_ellipse = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edit_halfaxis_big_ellipse.setObjectName("edit_halfaxis_big_ellipse")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edit_halfaxis_big_ellipse)
        self.label_big_halfaxis_ellipse_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_big_halfaxis_ellipse_2.setObjectName("label_big_halfaxis_ellipse_2")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_big_halfaxis_ellipse_2)
        self.edit_halfaxis_low_ellipse = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edit_halfaxis_low_ellipse.setObjectName("edit_halfaxis_low_ellipse")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.edit_halfaxis_low_ellipse)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(7, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.label_algorithm_ellipse = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_algorithm_ellipse.setObjectName("label_algorithm_ellipse")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_algorithm_ellipse)
        self.box_algorithm_ellipse = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.box_algorithm_ellipse.setObjectName("box_algorithm_ellipse")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.box_algorithm_ellipse)
        self.label_colour_ellipse = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_colour_ellipse.setObjectName("label_colour_ellipse")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_colour_ellipse)
        self.box_colour_ellipse = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.box_colour_ellipse.setObjectName("box_colour_ellipse")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.box_colour_ellipse)
        spacerItem4 = QtWidgets.QSpacerItem(20, 143, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(10, QtWidgets.QFormLayout.SpanningRole, spacerItem4)
        self.label_build_spectrum_ellipse = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_build_spectrum_ellipse.setAlignment(QtCore.Qt.AlignCenter)
        self.label_build_spectrum_ellipse.setObjectName("label_build_spectrum_ellipse")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.label_build_spectrum_ellipse)
        self.label_step_change_ellipse = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_step_change_ellipse.setIndent(20)
        self.label_step_change_ellipse.setObjectName("label_step_change_ellipse")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.SpanningRole, self.label_step_change_ellipse)
        self.edit_step_change_big_halfaxis = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edit_step_change_big_halfaxis.setObjectName("edit_step_change_big_halfaxis")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.edit_step_change_big_halfaxis)
        self.edit_step_change_low_halfaxis = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edit_step_change_low_halfaxis.setObjectName("edit_step_change_low_halfaxis")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.edit_step_change_low_halfaxis)
        self.label_count_ellipses = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_count_ellipses.setIndent(19)
        self.label_count_ellipses.setObjectName("label_count_ellipses")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_count_ellipses)
        self.edit_count_ellipses = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.edit_count_ellipses.setObjectName("edit_count_ellipses")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.edit_count_ellipses)
        spacerItem5 = QtWidgets.QSpacerItem(20, 123, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout_2.setItem(16, QtWidgets.QFormLayout.SpanningRole, spacerItem5)
        self.but_create_ellipse = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.but_create_ellipse.setObjectName("but_create_ellipse")
        self.formLayout_2.setWidget(17, QtWidgets.QFormLayout.SpanningRole, self.but_create_ellipse)
        self.but_create_spectrum_ellipse = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.but_create_spectrum_ellipse.setObjectName("but_create_spectrum_ellipse")
        self.formLayout_2.setWidget(18, QtWidgets.QFormLayout.SpanningRole, self.but_create_spectrum_ellipse)
        self.but_clear_ellipse = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.but_clear_ellipse.setObjectName("but_clear_ellipse")
        self.formLayout_2.setWidget(19, QtWidgets.QFormLayout.SpanningRole, self.but_clear_ellipse)
        self.radiobut_big_halfaxis = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radiobut_big_halfaxis.setObjectName("radiobut_big_halfaxis")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.radiobut_big_halfaxis)
        self.radiobut_low_halfaxis = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radiobut_low_halfaxis.setObjectName("radiobut_low_halfaxis")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.radiobut_low_halfaxis)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1920, 24))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setEnabled(True)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.action_info = QtWidgets.QAction(MainWindow)
        self.action_info.setObjectName("action_info")
        self.action_cancel = QtWidgets.QAction(MainWindow)
        self.action_cancel.setObjectName("action_cancel")
        self.analyze_circle_time = QtWidgets.QAction(MainWindow)
        self.analyze_circle_time.setObjectName("analyze_circle_time")
        self.analyze_ellipse_time = QtWidgets.QAction(MainWindow)
        self.analyze_ellipse_time.setObjectName("analyze_ellipse_time")
        self.menu_2.addAction(self.analyze_circle_time)
        self.menu_2.addAction(self.analyze_ellipse_time)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_create_circle.setText(_translate("MainWindow", "Построение окружности"))
        self.label_center_circle.setText(_translate("MainWindow", "Координаты центра"))
        self.label_center_x_circle.setText(_translate("MainWindow", "          x"))
        self.label_center_y_circle.setText(_translate("MainWindow", "          y"))
        self.label_radius_circle.setText(_translate("MainWindow", "      Радиус"))
        self.label_algorithm_circle.setText(_translate("MainWindow", "    Алгоритм"))
        self.label_colour_circle.setText(_translate("MainWindow", "          Цвет"))
        self.label_create_spectrum_circle.setText(_translate("MainWindow", "Построение концентрических окружностей"))
        self.label_start_radius_circle.setText(_translate("MainWindow", "Начальный\n"
"радиус"))
        self.label_step_change_circle.setText(_translate("MainWindow", "Шаг\n"
"изменения\n"
"радиуса"))
        self.radiobut_end_radius.setText(_translate("MainWindow", "Конечный\n"
"радиус"))
        self.radiobut_count_circles.setText(_translate("MainWindow", "Количество\n"
"окружностей"))
        self.but_create_circle.setText(_translate("MainWindow", "Построить окружность"))
        self.but_create_spectrum_circle.setText(_translate("MainWindow", "Построить спектр"))
        self.but_clear_circle.setText(_translate("MainWindow", "Очистить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Окружность"))
        self.label_build_ellipse.setText(_translate("MainWindow", "Построение эллипса"))
        self.label_center_ellipse.setText(_translate("MainWindow", "Координаты центра"))
        self.label_center_x_ellipse.setText(_translate("MainWindow", "          x"))
        self.label_center_y_ellipse.setText(_translate("MainWindow", "          y"))
        self.label_value_halfaxis_ellipse.setText(_translate("MainWindow", "                             Значение полуосей"))
        self.label_big_halfaxis_ellipse.setText(_translate("MainWindow", "       Большая"))
        self.label_big_halfaxis_ellipse_2.setText(_translate("MainWindow", "       Малая"))
        self.label_algorithm_ellipse.setText(_translate("MainWindow", "    Алгоритм"))
        self.label_colour_ellipse.setText(_translate("MainWindow", "          Цвет"))
        self.label_build_spectrum_ellipse.setText(_translate("MainWindow", "Построение спектра\n"
"концентрических эллипсов"))
        self.label_step_change_ellipse.setText(_translate("MainWindow", "Шаг изменения полуоси"))
        self.label_count_ellipses.setText(_translate("MainWindow", "Количество\n"
"эллипсов"))
        self.but_create_ellipse.setText(_translate("MainWindow", "Построить эллипс"))
        self.but_create_spectrum_ellipse.setText(_translate("MainWindow", "Построить спектр"))
        self.but_clear_ellipse.setText(_translate("MainWindow", "Очистить"))
        self.radiobut_big_halfaxis.setText(_translate("MainWindow", "Большой"))
        self.radiobut_low_halfaxis.setText(_translate("MainWindow", "Малой"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Эллипс"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Анализ"))
        self.action_info.setText(_translate("MainWindow", "Справка"))
        self.action_cancel.setText(_translate("MainWindow", "Отменить"))
        self.analyze_circle_time.setText(_translate("MainWindow", "Спектра окружности"))
        self.analyze_ellipse_time.setText(_translate("MainWindow", "Спектра эллипса"))
