# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab_03.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 920)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setEnabled(True)
        self.graphicsView.setMinimumSize(QtCore.QSize(1500, 0))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(50, -1, 46, -1)
        self.verticalLayout_4.setSpacing(8)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_4.addItem(spacerItem)
        self.label_build_lines = QtWidgets.QLabel(self.centralwidget)
        self.label_build_lines.setObjectName("label_build_lines")
        self.verticalLayout_4.addWidget(self.label_build_lines)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_begin = QtWidgets.QLabel(self.centralwidget)
        self.label_begin.setObjectName("label_begin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_begin)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.edit_start_x = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_start_x.setObjectName("edit_start_x")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edit_start_x)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.edit_start_y = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_start_y.setObjectName("edit_start_y")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edit_start_y)
        spacerItem1 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.SpanningRole, spacerItem1)
        self.label_end = QtWidgets.QLabel(self.centralwidget)
        self.label_end.setObjectName("label_end")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_end)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.edit_end_x = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_end_x.setObjectName("edit_end_x")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edit_end_x)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.edit_end_y = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_end_y.setObjectName("edit_end_y")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.edit_end_y)
        spacerItem2 = QtWidgets.QSpacerItem(20, 19, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.SpanningRole, spacerItem2)
        self.label_algorithm = QtWidgets.QLabel(self.centralwidget)
        self.label_algorithm.setObjectName("label_algorithm")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_algorithm)
        self.combo_algorithm = QtWidgets.QComboBox(self.centralwidget)
        self.combo_algorithm.setObjectName("combo_algorithm")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.combo_algorithm)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(17, QtWidgets.QFormLayout.SpanningRole, spacerItem3)
        self.button_process = QtWidgets.QPushButton(self.centralwidget)
        self.button_process.setObjectName("button_process")
        self.formLayout.setWidget(18, QtWidgets.QFormLayout.SpanningRole, self.button_process)
        spacerItem4 = QtWidgets.QSpacerItem(20, 111, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(19, QtWidgets.QFormLayout.SpanningRole, spacerItem4)
        self.label_spectrum = QtWidgets.QLabel(self.centralwidget)
        self.label_spectrum.setObjectName("label_spectrum")
        self.formLayout.setWidget(20, QtWidgets.QFormLayout.SpanningRole, self.label_spectrum)
        self.label_length = QtWidgets.QLabel(self.centralwidget)
        self.label_length.setObjectName("label_length")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.label_length)
        self.edit_length = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_length.setObjectName("edit_length")
        self.formLayout.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.edit_length)
        self.label_angle = QtWidgets.QLabel(self.centralwidget)
        self.label_angle.setObjectName("label_angle")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.LabelRole, self.label_angle)
        self.edit_angle = QtWidgets.QLineEdit(self.centralwidget)
        self.edit_angle.setObjectName("edit_angle")
        self.formLayout.setWidget(22, QtWidgets.QFormLayout.FieldRole, self.edit_angle)
        self.button_build_spectrum = QtWidgets.QPushButton(self.centralwidget)
        self.button_build_spectrum.setObjectName("button_build_spectrum")
        self.formLayout.setWidget(23, QtWidgets.QFormLayout.SpanningRole, self.button_build_spectrum)
        self.combo_colour = QtWidgets.QComboBox(self.centralwidget)
        self.combo_colour.setObjectName("combo_colour")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.combo_colour)
        self.button_clean = QtWidgets.QPushButton(self.centralwidget)
        self.button_clean.setObjectName("button_clean")
        self.formLayout.setWidget(25, QtWidgets.QFormLayout.SpanningRole, self.button_clean)
        spacerItem5 = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(24, QtWidgets.QFormLayout.SpanningRole, spacerItem5)
        self.verticalLayout_4.addLayout(self.formLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_info = QtWidgets.QAction(MainWindow)
        self.action_info.setObjectName("action_info")
        self.action_cancel = QtWidgets.QAction(MainWindow)
        self.action_cancel.setObjectName("action_cancel")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_build_lines.setText(_translate("MainWindow", "Построение отрезка"))
        self.label_begin.setText(_translate("MainWindow", "Начало отрезка"))
        self.label.setText(_translate("MainWindow", "x"))
        self.label_2.setText(_translate("MainWindow", "y"))
        self.label_end.setText(_translate("MainWindow", "Конец отрезка"))
        self.label_4.setText(_translate("MainWindow", "x"))
        self.label_5.setText(_translate("MainWindow", "y"))
        self.label_algorithm.setText(_translate("MainWindow", "Алгоритм"))
        self.label_6.setText(_translate("MainWindow", "Цвет"))
        self.button_process.setText(_translate("MainWindow", "Построить\n"
"отрезок"))
        self.label_spectrum.setText(_translate("MainWindow", "Построение спектра отрезков"))
        self.label_length.setText(_translate("MainWindow", "Длина"))
        self.label_angle.setText(_translate("MainWindow", "Угол"))
        self.button_build_spectrum.setText(_translate("MainWindow", "Построить\n"
"спектр"))
        self.button_clean.setText(_translate("MainWindow", "Очистить"))
        self.action_info.setText(_translate("MainWindow", "Справка"))
        self.action_cancel.setText(_translate("MainWindow", "Отменить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
